### ISSUE TITLE
Virker ikke mere efter update til HA 2024.11.0

### ISSUE THREAD

**Issue by VagnPetersen** [briis/affalddk#177]
### Describe the issue

Fejl ved start efter update til core-2024.11.0

### What version of Home Assistant Core has the issue?

core-2024.11.0

### What was the last working version of Home Assistant Core?

core-2024,10

### What type of installation are you running?

Home Assistant Supervised

### What version of the integration are you using?

2.1.19

### Diagnostics information

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 09:18:54 (1 occurrences)
Last logged: 09:18:54

Setup failed for custom integration 'affalddk': Unable to import component: No module named 'pyaffalddk'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/affalddk/__init__.py", line 9, in <module>
    from pyaffalddk import (
ModuleNotFoundError: No module named 'pyaffalddk'

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 09:18:54 (1 occurrences)
Last logged: 09:18:54

Setup failed for custom integration 'affalddk': Unable to import component: No module named 'pyaffalddk'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/affalddk/__init__.py", line 9, in <module>
    from pyaffalddk import (
ModuleNotFoundError: No module named 'pyaffalddk'
```

**Comment by briis** [comment]
Dette kan jeg ikke genskabe. Jeg har opdateret 3 x Home Assistant til 2024.11 uden at få det problem. Integrationen virker perfekt her. `pyaffalddk` er et ekstra modul der hentes fra Github, er du sikker på din HA har internet adgang?

Ellers har jeg nok ikke andre forslag end at afinstallere AffaldDK, genstarte Home Assistant og så installere igen.

**Comment by VagnPetersen** [comment]
Jeg har internetadgang og alt andet i HA kører perfekt.
Jeg har prøvet af afinstallere og geninstallere AffaldDK, men jeg får stadig en fejl med, at pyaffalddk modulet mangler.
På Github - under affalddk, kan jeg ikke se modulet nogen steder?

**Comment by briis** [comment]
Jeg har lige testet igen og kan stadig ikke fremprovokere denne fejl, og du er også den eneste der har rapporteret den, så der må være et eller andet idin specifikke installation der gør dette.
Hvis du nu prøvet at afinstallere igen, også i HACS. Når det er gjort, åbner eksempelvis Visual Studio i Home Assistant (Eller en anden editor) og så går til mappen `custom_components`. Hvis der stadig er en mappe kaldet affalddk, så prøv at slette denne og alle undermapper.
Så genstarter du Home Assistant og starter med installationen fra HACS, genstarter og så tilføjer Integrationen en gang til.

Dette er den eneste måde vi kan være sikker på der ikke ligger gamle filer i systemet.

**Comment by VagnPetersen** [comment]
Jeg har prøvet alt.
Fjernet custom_components, genstartet og genintalleret. Intet virker.
Alt virkede før jeg opdaterede til 2024.11.0.
Alle mine andre dele af HA virker, så jeg er desværre nok nødt til at sige farvel til affalddk :(

**Comment by VagnPetersen** [comment]
OK, her følger en lidt længere redegørelse for mine observationer:
1. Jeg fjernede alle spor fra Affalddk from min HA installation. Brugte WinSCR til at fjerne og kontrollere om der var nogle spor tilbage på min HA. Inger biblioteker og ingen filer tilbage efter min sidste installation.
2. Gennemførte en ny installation fuldstændig som anvist i readme filen. Først blev custom_components tilføjet.
3. HA genstartet.
4. Integrationen AffaldDK blev forsøgt kørt og følgende fejl kommer: "Config flow could not be loaded: {"message":"Invalid handler specified"}"
5. Ved at læse din "init_py" fil på Github og i installationsfolderen fremgår følgende kode (line 9):
from pyaffalddk import (
    GarbageCollection,
    PickupEvents,
    AffaldDKNotSupportedError,
    AffaldDKNotValidAddressError,
    AffaldDKNoConnection,

Imidlertid er der ingen fil kaldet "pyaffalddk" i hverken installationsfolderen eller på Github.
Mangler der ikke noget???

**Comment by VagnPetersen** [comment]
Jeg har netop opdateret min Core til 2024.11.2. Og nu virker Affalddk igen :)

**Comment by briis** [comment]
Det er fedt det virker igen. Det irriterer mig dog at jeg ikke kan finde en årsdag til dette.  Nedenstående fil læses af Home Assistant under opstart, og det der står under requirements, installerer HA automatisk fra et sted der hedder https://pypi.org

Jeg ved faktisk ikke præcis hvor den placerer denne fil, men mit bedste gæt er at dit system har troet den er der, uden at den har været hentet.

Nå, men glad for det virker igen.

```json
{
    "domain": "affalddk",
    "name": "Affaldshåndtering DK",
    "after_dependencies": [
        "http"
    ],
    "codeowners": [
        "@briis"
    ],
    "config_flow": true,
    "documentation": "https://github.com/briis/affalddk",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/briis/affalddk/issues",
    "requirements": [
        "pyaffalddk==2.0.41"
    ],
    "version": "2.1.19"
}
````

**Comment by VagnPetersen** [comment]
Ja, det irriterer også mig :)
Med den sidste update til HA, ser det ud til at virke. Det var ikke "kun" din integration, som gav problemer. Jeg havde også problemer med den sidste nye version af Frigate HACS integrationen. Dette kunne dog løses ved at installere en ældre version af denne integration.
Jeg er ret sikker på, at der var en fejl i forrige version af HA Core.

**Comment by newbenji** [comment]
Har samme problem.
Ligner i container den ikke altid installere fra requirements.
men lavede jeg manuelt en pip install affalddk så virkede det
